### ISSUE TITLE
Can't access kolab-webadmin on Kolab 16

### ISSUE THREAD

**Issue by zerpex** [kvaps/kolab-docker#22]
Hi,

Just tried a fresh install of Kolab 16 wiht docker-compose.
Everything seems to go well. I am able to access to roundcube, iRony... but the webadmin.

Each time the browser is redirected to "_/kolab-webadmin" and show a DNS error.
I tired many times with nginx or apache and ended with the same error.

Here is my docker-compose file (barely the default one):
```
version: '2'
services:
  kolab:
    restart: on-failure:1
    image: kvaps/kolab:16
    hostname: myhostname
    domainname: mydomain.tld
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./kolab/data:/data:rw
      - ./kolab/config:/config:rw
      - ./kolab/spool:/spool:rw
      - ./kolab/log:/log:rw
    tmpfs:
      - /run
    environment:
      - TZ=Europe/Paris
      - LDAP_ADMIN_PASS=5h7yAZo6A6Oep1pLLs0M1IOo
      - LDAP_MANAGER_PASS=5h7yAZo6A6Oep1pLLs0M1IOo
      - LDAP_CYRUS_PASS=5h7yAZo6A6Oep1pLLs0M1IOo
      - LDAP_KOLAB_PASS=5h7yAZo6A6Oep1pLLs0M1IOo
      - MYSQL_ROOT_PASS=5h7yAZo6A6Oep1pLLs0M1IOo
      - MYSQL_KOLAB_PASS=5h7yAZo6A6Oep1pLLs0M1IOo
      - MYSQL_ROUNDCUBE_PASS=5h7yAZo6A6Oep1pLLs0M1IOo
      - KOLAB_DEFAULT_LOCALE=fr_FR
    ports:
      - '80:80'
      - '443:443'
      - '25:25'
      - '587:587'
      - '110:110'
      - '995:995'
      - '143:143'
      - '993:993'
      - '4190:4190'
      - '389:389'
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    tty: true
```

=> it's installed on a fresh debian install that runs nothing else.

Any idea ?

zer
